version: 2.0

pipelines:
  - name: Build & Upload Flutter APK
    trigger_mode: ON_MANUAL
    ref_name: main

    actions:
      - name: Build Flutter APK
        image: ubuntu:20.04
        run:
          - apt-get update -y
          - apt-get install -y git wget unzip xz-utils curl
          - git clone https://github.com/flutter/flutter.git /opt/flutter
          - export PATH="$PATH:/opt/flutter/bin"
          - flutter channel stable
          - flutter upgrade
          - flutter config --enable-web
          - flutter create .          # ✅ هذا السطر يجعل Buddy يحدّث Android V2 تلقائيًا
          - flutter pub get
          - flutter build apk --release
          - ls -lah build/app/outputs/flutter-apk/

      - name: Upload APK Artifact
        action: artifacts/upload
        inputs:
          - source: "build/app/outputs/flutter-apk/app-release.apk"
